### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Hagonata** [voldemortX/pytorch-auto-drive#156]
```
python3 main_landet.py --train --config=configs/lane_detection/scnn/resnet101_culane.py --mixed-precision
/home/user/.local/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
/home/user/pytorch-auto-drive/utils/models/lane_detection/laneatt.py:22: UserWarning: Can't complie line nms op for LaneATT. Set verbose=True for load in /utils/csrc/apis.py L9 for details.
Loaded torchvision ImageNet pre-trained weights V1.
Not using distributed mode
cuda
Traceback (most recent call last):
  File "main_landet.py", line 77, in <module>
    runner.run()
  File "/home/user/pytorch-auto-drive/utils/runners/lane_det_trainer.py", line 35, in run
    for i, data in enumerate(self.dataloader, 0):
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/user/.local/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/pytorch-auto-drive/utils/datasets/lane_as_segmentation.py", line 43, in __getitem__
    target = Image.open(self.masks[index])
  File "/home/user/.local/lib/python3.8/site-packages/PIL/Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/user/LaCie/DataSet/CULane/laneseg_label_w16/driver_23_30frame/05170820_0712.MP4/00800.png'
```

First, why he is searching .png file, because in this folder only .txt files. I download CULane dataset from official google drive source.

**Comment by voldemortX** [comment]
@Hagonata You seem to be missing the seg labels

**Comment by Hagonata** [comment]
![Screenshot from 2023-08-29 11-28-09](https://github.com/voldemortX/pytorch-auto-drive/assets/95108691/6b99221e-924c-4ea6-b205-7e211966345b)

Is it correct?

> @Hagonata You seem to be missing the seg labels

**Comment by Hagonata** [comment]
I just don't understand why they are using .png

**Comment by voldemortX** [comment]
> I just don't understand why they are using .png

The segmentation labels are PNG files.

**Comment by Hagonata** [comment]
Thanks, I just think I need to use new annotations .tar.
