### ISSUE TITLE
训练时出错：TypeError: <module 'torch' from '/root/miniconda3/envs/pad2/lib/python3.6/site-packages/torch/__init__.py'> is not JSON serializable

### ISSUE THREAD

**Issue by Yuanxing-he** [voldemortX/pytorch-auto-drive#177]
Traceback (most recent call last):
  File "main_landet.py", line 75, in <module>
    runner = Runner(cfg=cfg)
  File "/root/pytorch-auto-drive-3.2.3/utils/runners/lane_det_trainer.py", line 17, in __init__
    super().__init__(cfg)
  File "/root/pytorch-auto-drive-3.2.3/utils/runners/base.py", line 120, in __init__
    self.init_exp_dir(cfg, 'train')
  File "/root/pytorch-auto-drive-3.2.3/utils/runners/base.py", line 93, in init_exp_dir
    f.write(json.dumps(cfg, indent=4))
TypeError: <module 'torch' from '/root/miniconda3/envs/pad2/lib/python3.6/site-packages/torch/__init__.py'> is not JSON serializable

**Comment by voldemortX** [comment]
> Traceback (most recent call last):
>   File "main_landet.py", line 75, in <module>
>     runner = Runner(cfg=cfg)
>   File "/root/pytorch-auto-drive-3.2.3/utils/runners/lane_det_trainer.py", line 17, in __init__
>     super().__init__(cfg)
>   File "/root/pytorch-auto-drive-3.2.3/utils/runners/base.py", line 120, in __init__
>     self.init_exp_dir(cfg, 'train')
>   File "/root/pytorch-auto-drive-3.2.3/utils/runners/base.py", line 93, in init_exp_dir
>     f.write(json.dumps(cfg, indent=4))
> TypeError: <module 'torch' from '/root/miniconda3/envs/pad2/lib/python3.6/site-packages/torch/__init__.py'> is not JSON serializable
> 

@Yuanxing-he 有运行的指令不，我看下

**Comment by Yuanxing-he** [comment]
python main_landet.py --train --config="/root/pytorch-auto-drive-3.2.3/configs/lane_detection/scnn/vgg16_culane.py" --mixed-precision @voldemortX

**Comment by voldemortX** [comment]
> python main_landet.py --train --config="/root/pytorch-auto-drive-3.2.3/configs/lane_detection/scnn/vgg16_culane.py" --mixed-precision @voldemortX 

感觉很奇怪。你的torch是正常能用的吗？
