### ISSUE TITLE
您好，我这边在用tusimple数据集跑Bezierlannet的训练时，命令是 python main_landet.py --train --config=configs/lane_detection/bezierlanenet/resnet18_tusimple_aug1b.py，出现了报错，请问您是否能提供解决方案或者建议呢？谢谢您！

### ISSUE THREAD

**Issue by Diamond88** [voldemortX/pytorch-auto-drive#180]
Traceback (most recent call last):
  File "main_landet.py", line 76, in <module>
    runner.run()
  File "/home/ubuntu/code/pytorch-auto-drive/utils/runners/lane_det_trainer.py", line 55, in run
    self.model)
  File "/home/ubuntu/anaconda3/envs/pad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/code/pytorch-auto-drive/utils/losses/hungarian_bezier_loss.py", line 150, in forward
    loss_seg = self.binary_seg_loss(inputs=outputs['segmentations'], targets=target_segmentations)
  File "/home/ubuntu/code/pytorch-auto-drive/utils/losses/hungarian_bezier_loss.py", line 204, in binary_seg_loss
    reduction='none') / self.pos_weight_seg
  File "/home/ubuntu/anaconda3/envs/pad/lib/python3.6/site-packages/torch/nn/functional.py", line 2538, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([20, 360, 640, 3])) must be the same as input size (torch.Size([20, 640, 3]))

**Comment by voldemortX** [comment]
> Traceback (most recent call last):
>   File "main_landet.py", line 76, in <module>
>     runner.run()
>   File "/home/ubuntu/code/pytorch-auto-drive/utils/runners/lane_det_trainer.py", line 55, in run
>     self.model)
>   File "/home/ubuntu/anaconda3/envs/pad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/ubuntu/code/pytorch-auto-drive/utils/losses/hungarian_bezier_loss.py", line 150, in forward
>     loss_seg = self.binary_seg_loss(inputs=outputs['segmentations'], targets=target_segmentations)
>   File "/home/ubuntu/code/pytorch-auto-drive/utils/losses/hungarian_bezier_loss.py", line 204, in binary_seg_loss
>     reduction='none') / self.pos_weight_seg
>   File "/home/ubuntu/anaconda3/envs/pad/lib/python3.6/site-packages/torch/nn/functional.py", line 2538, in binary_cross_entropy_with_logits
>     raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
> ValueError: Target size (torch.Size([20, 360, 640, 3])) must be the same as input size (torch.Size([20, 640, 3]))

@Diamond88 你这边有修改代码吗，还是直接跑的？

**Comment by Diamond88** [comment]
没有修改呢，就是下载的原代码和原数据直接跑的



---原始邮件---
发件人: "Zhengyang ***@***.***&gt;
发送时间: 2024年12月19日(周四) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [voldemortX/pytorch-auto-drive] 您好，我这边在用tusimple数据集跑Bezierlannet的训练时，命令是 python main_landet.py --train --config=configs/lane_detection/bezierlanenet/resnet18_tusimple_aug1b.py，出现了报错，请问您是否能提供解决方案或者建议呢？谢谢您！ (Issue #180)




  
Traceback (most recent call last):
 File "main_landet.py", line 76, in 
 runner.run()
 File "/home/ubuntu/code/pytorch-auto-drive/utils/runners/lane_det_trainer.py", line 55, in run
 self.model)
 File "/home/ubuntu/anaconda3/envs/pad/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
 result = self.forward(*input, **kwargs)
 File "/home/ubuntu/code/pytorch-auto-drive/utils/losses/hungarian_bezier_loss.py", line 150, in forward
 loss_seg = self.binary_seg_loss(inputs=outputs['segmentations'], targets=target_segmentations)
 File "/home/ubuntu/code/pytorch-auto-drive/utils/losses/hungarian_bezier_loss.py", line 204, in binary_seg_loss
 reduction='none') / self.pos_weight_seg
 File "/home/ubuntu/anaconda3/envs/pad/lib/python3.6/site-packages/torch/nn/functional.py", line 2538, in binary_cross_entropy_with_logits
 raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
 ValueError: Target size (torch.Size([20, 360, 640, 3])) must be the same as input size (torch.Size([20, 640, 3]))
  
@Diamond88 你这边有修改代码吗，还是直接跑的？

**Comment by voldemortX** [comment]
@Diamond88 奇怪，你可以尝试看一下模型输入时刻图片是否正常么，有h和w

**Comment by Diamond88** [comment]
好的好的，我看看输入是否有问题，谢谢您～



---原始邮件---
发件人: "Zhengyang ***@***.***&gt;
发送时间: 2024年12月19日(周四) 晚上7:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [voldemortX/pytorch-auto-drive] 您好，我这边在用tusimple数据集跑Bezierlannet的训练时，命令是 python main_landet.py --train --config=configs/lane_detection/bezierlanenet/resnet18_tusimple_aug1b.py，出现了报错，请问您是否能提供解决方案或者建议呢？谢谢您！ (Issue #180)




 
@Diamond88 奇怪，你可以尝试看一下模型输入时刻图片是否正常么，有h和w

**Comment by voldemortX** [comment]
@Diamond88 如果发现代码有bug欢迎pr修复
