### ISSUE TITLE
Problem with installation of CULanes dataset

### ISSUE THREAD

**Issue by Wakarox** [voldemortX/pytorch-auto-drive#80]
Hello,
I have a problem with the installation of the CULanes dataset.
When i do the "make" command, i have an "error opencv2/core/core.hpp : No such file or directory".
I have all the libraries on my computer but i am not using conda.
Can someone help me ?

**Comment by voldemortX** [comment]
@Wakarox Check if you have the c++ OpenCV on your system?

**Comment by Wakarox** [comment]
I am using cv2.
I commented the line 21 as the tutorial said.

**Comment by voldemortX** [comment]
> I am using cv2.
> I commented the line 21 as the tutorial said.

that is weird.  you sure it is not python opencv?

**Comment by Wakarox** [comment]
I have the error on the include of the library. I did an installation of opencv and have the files in /usr/local/includes. Maybe i have a problem with the path of the files ?

**Comment by voldemortX** [comment]
@Wakarox Can you display opencv version by `pkg-config --modversion opencv` ?

**Comment by Wakarox** [comment]
OpenCV is not found. I don't know why ...

**Comment by voldemortX** [comment]
> OpenCV is not found. I don't know why ...

It seems you may have a faulty installation of OpenCV. Are you using ubuntu, I think it can be installed via `apt-get`.

**Comment by Wakarox** [comment]
Not me. I don't know why :/

**Comment by voldemortX** [comment]
@Wakarox Perhaps try install opencv 2.x?

**Comment by Wakarox** [comment]
culane_list_convertor.py show something when running it?

**Comment by voldemortX** [comment]
> culane_list_convertor.py show something when running it?

nope. no printing means success, as in all Linux commands.

**Comment by Wakarox** [comment]
My error code :
pytorch-auto-drive/tools/culane_evaluation$ make
CXX src/lane_compare.cpp
In file included from include/lane_compare.hpp:4,
                 from src/lane_compare.cpp:8:
include/spline.hpp:6:10: fatal error: opencv2/core/core.hpp: Aucun fichier ou dossier de ce type
    6 | #include <opencv2/core/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40 : build/src/lane_compare.o] Erreur 1

**Comment by voldemortX** [comment]
> My error code : pytorch-auto-drive/tools/culane_evaluation$ make CXX src/lane_compare.cpp In file included from include/lane_compare.hpp:4, from src/lane_compare.cpp:8: include/spline.hpp:6:10: fatal error: opencv2/core/core.hpp: Aucun fichier ou dossier de ce type 6 | #include <opencv2/core/core.hpp> | ^~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make: *** [Makefile:40 : build/src/lane_compare.o] Erreur 1

I reproduced this error with a newly installed opencv4 from source. And I can make with adding `CXXFLAGS += -I/usr/local/include/opencv4`, for instance at [Line 22](https://github.com/voldemortX/pytorch-auto-drive/blob/76e83301e3ef1f245f9bc116566c017a816e229c/tools/culane_evaluation/Makefile#L22)

**Comment by Wakarox** [comment]
The include is now good, i found something like you said yesterday.
But now, i have a problem with the shared libraries.

CXX/LD evaluate
/usr/bin/ld: build/src/evaluate.o: undefined reference to symbol '_ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi'
/usr/bin/ld : /lib/x86_64-linux-gnu/libopencv_imgcodecs.so.4.2 : erreur lors de l'ajout de symboles : DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:44 : evaluate] Erreur 1

**Comment by voldemortX** [comment]
> The include is now good, i found something like you said yesterday. But now, i have a problem with the shared libraries.
> 
> CXX/LD evaluate /usr/bin/ld: build/src/evaluate.o: undefined reference to symbol '_ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi' /usr/bin/ld : /lib/x86_64-linux-gnu/libopencv_imgcodecs.so.4.2 : erreur lors de l'ajout de symboles : DSO missing from command line collect2: error: ld returned 1 exit status make: *** [Makefile:44 : evaluate] Erreur 1

As far as I know, this might be caused by installing multiple versions of opencv. For instance, when I install opencv3 from apt and sudo install the opencv4 zip, I see a similar error.

**Comment by Wakarox** [comment]
So you suggest me to unistall opencv, and reinstall it ?

**Comment by voldemortX** [comment]
In my case I uninstalled the apt one.

**Comment by Wakarox** [comment]
I tried to unistall it, it didn't work, i always have the same issue... I am searching a way to link that .so but all i tried didn't work too

**Comment by voldemortX** [comment]
@Wakarox I think you can search for opencv installation issues in general, since this probably is not specific to these codes. If you really can't make it work, you can try use `culane_evaluation_py` instead. I believe [LaneATT](https://github.com/lucastabelini/LaneATT/blob/main/utils/culane_metric.py) have a full python version. But it slightly misalign with the cpp version.

**Comment by Wakarox** [comment]
I have a new error when i changed the Makefile deleting the 2 lines of condition:


CXX/LD evaluate
/usr/bin/ld : build/src/lane_compare.o : dans la fonction « LaneCompare::get_lane_similarity(std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&, std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&) » :
lane_compare.cpp:(.text+0x56e) : référence indéfinie vers « cv::_InputArray::_InputArray(cv::MatExpr const&) »
/usr/bin/ld : build/src/lane_compare.o : dans la fonction « cv::MatExpr::operator cv::Mat() const » :
lane_compare.cpp:(.text._ZNK2cv7MatExprcvNS_3MatEEv[_ZNK2cv7MatExprcvNS_3MatEEv]+0x2c) : référence indéfinie vers « cv::Mat::Mat() »
collect2: error: ld returned 1 exit status
make: *** [Makefile:43 : evaluate] Erreur 1

**Comment by voldemortX** [comment]
@Wakarox At this point, I'd suggest you clean your environment of any opencv related stuff, delete the build dir in `culane_evaluation`. Then install opencv via the opencv documentation, and use the last step `sudo make install` to install it in /usr. If you installed opencv4 (their latest version), add the Line 22 like I did and it should work fine.

Alternatively, `apt install libopencv-dev` might also work but I don't really know.

**Comment by Wakarox** [comment]
That's good now, i found a solution (adding the library in the Makefile).
Now, i am blocked with the config of lane detection.

mokhtarbouain@iris-Precision-Tower-7810:~/Documents/Python_scripts/pytorch-auto-drive$ python3 main_landet.py --config=/home/mokhtarbouain/Téléchargements/resnet18-5c106cde.pth 
Traceback (most recent call last):
  File "main_landet.py", line 11, in <module>
    from utils.args import parse_arg_cfg, read_config, map_states, add_shortcuts, cmd_dict
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/__init__.py", line 4, in <module>
    from . import models
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/__init__.py", line 16, in <module>
    from .swin import SwinTransformer
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/swin.py", line 13, in <module>
    from timm.models.layers import DropPath, to_2tuple, trunc_normal_
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/timm/models/__init__.py", line 1, in <module>
    from .cspnet import *
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/timm/models/cspnet.py", line 20, in <module>
    from .helpers import build_model_with_cfg
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/timm/models/helpers.py", line 17, in <module>
    from .layers import Conv2dSame, Linear
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/timm/models/layers/__init__.py", line 7, in <module>
    from .cond_conv2d import CondConv2d, get_condconv_initializer
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/timm/models/layers/cond_conv2d.py", line 16, in <module>
    from .helpers import to_2tuple
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/timm/models/layers/helpers.py", line 6, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/home/mokhtarbouain/.local/lib/python3.8/site-packages/torch/_six.py)

**Comment by voldemortX** [comment]
@Wakarox Good to know you made opencv work!

It seems your timm version doesn't support your pytorch version. Do you have pytorch > 1.8? It looks the same issue as in this one:

https://github.com/voldemortX/pytorch-auto-drive/issues/37

**Comment by Wakarox** [comment]
Done.
Now, i have another error, i am not sure but i think it's mmcv.
mokhtarbouain@iris-Precision-Tower-7810:~/Documents/Python_scripts/pytorch-auto-drive$ python3 main_landet.py --config=/home/mokhtarbouain/Téléchargements/resnet18-5c106cde.pth 
Traceback (most recent call last):
  File "main_landet.py", line 11, in <module>
    from utils.args import parse_arg_cfg, read_config, map_states, add_shortcuts, cmd_dict
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/__init__.py", line 2, in <module>
    from . import losses
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/losses/__init__.py", line 3, in <module>
    from .hungarian_loss import HungarianLoss
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/losses/hungarian_loss.py", line 10, in <module>
    from ..models.lane_detection import cubic_curve_with_projection
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/__init__.py", line 7, in <module>
    from . import segmentation
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/segmentation/__init__.py", line 5, in <module>
    from .erfnet import ERFNet
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/segmentation/erfnet.py", line 10, in <module>
    from ..common_models import non_bottleneck_1d
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/common_models/__init__.py", line 1, in <module>
    from .blocks import *
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/common_models/blocks/__init__.py", line 1, in <module>
    from .inverted_residual import InvertedResidual, InvertedResidualV3
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/common_models/blocks/inverted_residual.py", line 3, in <module>
    from ..plugins import SELayer
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/common_models/plugins/__init__.py", line 6, in <module>
    from .feature_flip_fusion import FeatureFlipFusion, DCN_v2_Ref
  File "/home/mokhtarbouain/Documents/Python_scripts/pytorch-auto-drive/utils/models/common_models/plugins/feature_flip_fusion.py", line 3, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d  # DCNv2
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/mokhtarbouain/.local/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/mokhtarbouain/.local/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v

**Comment by Wakarox** [comment]
I tried reinstalling mmcv but the "requirements already satisfied".
I am not working on conda because i will try (after lauching it and testing it) to add it in a ROS environnement.

**Comment by voldemortX** [comment]
> I tried reinstalling mmcv but the "requirements already satisfied". I am not working on conda because i will try (after lauching it and testing it) to add it in a ROS environnement.

If you are using pip, first `pip uninstall mmcv-full`, then install the correct version.

**Comment by Wakarox** [comment]
Hello,
I don't have any errors now, now, i want to use a pre-trained weight, but i didn't saw how to do it in the README.
Can you explain me pls ?

**Comment by voldemortX** [comment]
> Hello, I don't have any errors now, now, i want to use a pre-trained weight, but i didn't saw how to do it in the README. Can you explain me pls ?

You can download the pre-trained weights available from the [model zoo](https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/MODEL_ZOO.md), where you can see blue [model]() as links. And test with them by `--checkpoint=<path to .pt file>`

**Comment by Wakarox** [comment]
It is good, i can try to train, but the problem now is the setup, because my graphic card is a Quadro M2000. I had an error when training :
RuntimeError: CUDA out of memory. Tried to allocate 142.00 MiB (GPU 0; 3.94 GiB total capacity; 3.05 GiB already allocated; 95.50 MiB free; 3.13 GiB reserved in total by PyTorch)
Can i do something to success the train ?

**Comment by voldemortX** [comment]
@Wakarox You should start from batch size 1 (better with mixed precision if possible), gradually increase it until your gpu memory is full. Then adjust learning rate, usually by linear (e. g. bs 20 to 4, lr should be divoded by 5) or sqrt (same example divide by sqrt(5)).

**Comment by Wakarox** [comment]
Hello @voldemortX ,
That's good now, i want to visualize the result in real time, it's possible with your code ?

**Comment by voldemortX** [comment]
> Hello @voldemortX ,
> That's good now, i want to visualize the result in real time, it's possible with your code ?

By in real-time do you mean camera inputs? If so we do not support that currently.  But we do support visualizing a folder of images or video, it would not be hard to adapt to camera input. 

You can refer to: https://www.github.com/voldemortX/pytorch-auto-drive/tree/master/docs/VISUALIZATION.md

**Comment by Wakarox** [comment]
In ROS, i use rosbag to play a record of our vehicle. Now, i want to use these bags with your program.

**Comment by voldemortX** [comment]
@Wakarox Sorry I don't know much about rosbag, but if the input format does not match the current visualization format, you'll have to adjust the APIs yourself to connect these programs. Perhaps you will need to write a new vis `Runner` or expose some API functions from PytorchAutoDrive based on your use case. 

If you made some addtions that would benefit ros integration, I'd be more than happy to take pull requests.

**Comment by Wakarox** [comment]
I will try to use only one config pretrained (resnet18_culane). I need to filter the files for this config. What files i will need to keep ?

**Comment by voldemortX** [comment]
> I will try to use only one config pretrained (resnet18_culane). I need to filter the files for this config. What files i will need to keep ?

I think you need the entry file, transforms and model definitions (including the config).  And lane runner & dataset if training or testing are still required.  In fact, best way is find the important files and keep others through `import`.

**Comment by Wakarox** [comment]
Hello @voldemortX ,
I have a question for visualization, can i use just a test image without keypoints txt for checking the accuracy of the program ?

**Comment by Wakarox** [comment]
Hello @voldemortX 
Where i can find the coordinates of the points ?
I am using a model without curve equation, i will add it myself.

**Comment by voldemortX** [comment]
@Wakarox Perhaps get them somewhere around here? https://github.com/voldemortX/pytorch-auto-drive/blob/76e83301e3ef1f245f9bc116566c017a816e229c/utils/vis_utils.py#L93

**Comment by Wakarox** [comment]
> @Wakarox Perhaps get them somewhere around here? Before they were drawn.
> 
> https://github.com/voldemortX/pytorch-auto-drive/blob/76e83301e3ef1f245f9bc116566c017a816e229c/utils/vis_utils.py#L93
> 
> If you are using dataset inference, you can find things in `./output`

Hello,
I am trying to add your code in ROS, but i need to know if all the parameters in this function are necessary.
I want to use my own images with the predict function, but i want to keep the dataset module for training and testing on my own dataset.
I modified some files to reduce the quantity of code, but it's not enough yet, and i am a little lost.
If you need to see my change, i will send you my code.
Best Regards,

**Comment by voldemortX** [comment]
@Wakarox Can I maybe see your change in git? I could suggest what more could be deleted when I go through them.

**Comment by Wakarox** [comment]
I just created a Git for this application : https://github.com/Wakarox/pytorch_auto_drive_ros
I deleted a lot of semantic segmentation code and i just begin to modify lane detection.
For the moment, i didn't push all the ROS environment, i will do it later.

**Comment by voldemortX** [comment]
@Wakarox It would be best if it can include the git history of pytorch_auto_drive so it can indicate which files are deleted already. Nevertheless, I will probably go through them before the weekend.

**Comment by Wakarox** [comment]
Hello,
I forgot to push the downloaded version, but all you have on GitHub is for lane detection.
I am trying to add your code on ROS, but i have errors that i am trying to debug.

**Comment by Wakarox** [comment]
Now, i need to put a fixed pre-trained weights in the code, put a fixed config, and do an input and an output in real-time.

**Comment by voldemortX** [comment]
> Now, i need to put a fixed pre-trained weights in the code, put a fixed config, and do an input and an output in real-time.

Which config file would you like to keep?  If that is specified.  it would be easier to delete redundant codes

**Comment by Wakarox** [comment]
For the moment, i am using baseline_resnet18_tusimple

**Comment by Wakarox** [comment]
But i don't find where you do your --config and --checkpoint in the code to have a single config

**Comment by voldemortX** [comment]
@Wakarox Sorry I can't download your ros project (bad network connection and you have a big checkpoint file in it). I did about all I could for a file-level deletion, hope it would suffice (If you get into errors, try patch up the missing things with the master branch or delete some redundant imports should do the trick). Here: https://github.com/voldemortX/pytorch-auto-drive/tree/resnet18-tusimple

If you want to go deeper, you will have to delete visualization codes, onnx/trt conversion codes, profiling codes, or get into deleting part of some files.

**Comment by voldemortX** [comment]
> Hello @voldemortX , I am using visualization code because i want to see in real-time the updates. Is this wrong ? I deleted LaneDetVideo because i think LaneDetDir is already taking picture by picture. But for the moment, i didn't delete any files concerning lane detection.

That should be correct. But you can mod them to only inference if you don't really need to draw anything.

**Comment by Wakarox** [comment]
So i can't use prediction ?

**Comment by voldemortX** [comment]
> So i can't use prediction ?

Could you elaborate on this? I don't quite get the meaning.

**Comment by Wakarox** [comment]
I am using the model baseline_resnet18_tusimple with his pretrained weights.
I want to predict the lines in my records with this configuration.

**Comment by voldemortX** [comment]
> I am using the model baseline_resnet18_tusimple with his pretrained weights.
> I want to predict the lines in my records with this configuration using my ros records, so in real time.

Well I think this usage aligns more with the visualization codes.

**Comment by Wakarox** [comment]
And later, with all the points, i will calculate the curvature of the lines. So i want to know where the points are calculated. And i want to delete the args, so i need to add config, input and output in the same file. For the moment, when i launch with rosrun, i have this error :
[ERROR] [1652861251.852334]: bad callback: <bound method listener.callback of <__main__.listener object at 0x7fd4381075b0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/mokhtarbouain/Documents/work_lane_detection/src/Deep_Learning_detection_lane/scripts/deep_learning_lane_detection.py", line 29, in callback
    cv2_image = LaneDetDir(LaneDetVisualizer)
  File "/home/mokhtarbouain/Documents/work_lane_detection/src/common_tools_pkg/src/common_tools_pkg/utils/runners/lane_det_visualizer.py", line 85, in __init__
    super().__init__(cfg)
  File "/home/mokhtarbouain/Documents/work_lane_detection/src/common_tools_pkg/src/common_tools_pkg/utils/runners/base.py", line 245, in __init__
    super().__init__(cfg)
  File "/home/mokhtarbouain/Documents/work_lane_detection/src/common_tools_pkg/src/common_tools_pkg/utils/runners/base.py", line 45, in __init__
    self.model = MODELS.from_dict(cfg['model'])
TypeError: 'ABCMeta' object is not subscriptable

I thought it's because my input is just the picture and not all the configs what i need to launch the detection lane code.
Maybe you could help me ?

**Comment by voldemortX** [comment]
Sorry I don't think I know this kind of error. Maybe there are some problems because of the deletions? If you don't want configs, you can use the Classes yourself by putting in __init__() args according to the configs.

**Comment by Rsweater** [comment]
You can see if there is opencv2 under `/usr/include`, if not, see if it contains `opencv4/opencv2`, if so, you can use `sudo ln -s /usr/include/opencv4/opencv2` /usr/include/ to link it directly to the parent directory.

**Comment by shifan-Z** [comment]
> The include is now good, i found something like you said yesterday. But now, i have a problem with the shared libraries.
> 
> CXX/LD evaluate /usr/bin/ld: build/src/evaluate.o: undefined reference to symbol '_ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi' /usr/bin/ld : /lib/x86_64-linux-gnu/libopencv_imgcodecs.so.4.2 : erreur lors de l'ajout de symboles : DSO missing from command line collect2: error: ld returned 1 exit status make: *** [Makefile:44 : evaluate] Erreur 1

I encountered the same issue, and my solution was to check the installation path of the openCV library files and modify the Makefile's LIBRARY_DIRS to /usr/local/lib.

**Comment by zdc233** [comment]
I meet the same problem, there is a solution you can try it.

Some versions about opencv in my ubuntu are given here:

```
(pad) cluster@cluster-System:~/zdc233$ pip list | grep opencv
opencv-python           4.5.4.58
(pad) cluster@cluster-System:~/zdc233$ pkg-config --modversion opencv4
4.5.4
(pad) cluster@cluster-System:~/zdc233$ ls /usr/include/ | grep opencv
opencv4
```

Then, you can add these commond in your Makefile(pytorch-auto-drive/tools/culane_evaluation/Makefile)
```
export CPLUS_INCLUDE_PATH=/usr/include/opencv4:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=/usr/lib:$LIBRARY_PATH
```
Finally, use commond "make", the problem should be solved.

There is my Makefile you can refer:

```
PROJECT_NAME:= evaluate

# config ----------------------------------

INCLUDE_DIRS := include
LIBRARY_DIRS := lib

COMMON_FLAGS := -DCPU_ONLY
CXXFLAGS := -std=c++11 -fopenmp
LDFLAGS := -fopenmp -Wl,-rpath,./lib

BUILD_DIR := build

# make rules -------------------------------
CXX ?= g++
BUILD_DIR ?= ./build

LIBRARIES += opencv_core opencv_highgui opencv_imgproc

# Comment Line 21 if using opencv2
LIBRARIES += opencv_imgcodecs
export CPLUS_INCLUDE_PATH=/usr/include/opencv4:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=/usr/lib:$LIBRARY_PATH

CXXFLAGS += $(COMMON_FLAGS) $(foreach includedir,$(INCLUDE_DIRS),-I$(includedir))
LDFLAGS +=  $(COMMON_FLAGS) $(foreach includedir,$(LIBRARY_DIRS),-L$(includedir)) $(foreach library,$(LIBRARIES),-l$(library))
SRC_DIRS += $(shell find * -type d -exec bash -c "find {} -maxdepth 1 \( -name '*.cpp' -o -name '*.proto' \) | grep -q ." \; -print)
CXX_SRCS += $(shell find src/ -name "*.cpp")
CXX_TARGETS:=$(patsubst %.cpp, $(BUILD_DIR)/%.o, $(CXX_SRCS))
ALL_BUILD_DIRS := $(sort $(BUILD_DIR) $(addprefix $(BUILD_DIR)/, $(SRC_DIRS)))

.PHONY: all
all: $(PROJECT_NAME)

.PHONY: $(ALL_BUILD_DIRS)
$(ALL_BUILD_DIRS):
	@mkdir -p $@

$(BUILD_DIR)/%.o: %.cpp | $(ALL_BUILD_DIRS)
	@echo "CXX" $<
	@$(CXX) $(CXXFLAGS) -c -o $@ $<

$(PROJECT_NAME): $(CXX_TARGETS)
	@echo "CXX/LD" $@
	@$(CXX) -o $@ $^ $(LDFLAGS)

.PHONY: clean
clean:
	@rm -rf $(CXX_TARGETS)
	@rm -rf $(PROJECT_NAME)
	@rm -rf $(BUILD_DIR)


```
